parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\MongoDBClient:
        arguments:
            $dsn: 'mongodb://localhost:27017'

    App\Service\UserService:
        arguments:
            $dsn: 'mongodb://localhost:27017'

    App\Service\MailService:
        arguments:
            $mailerMailSender: '%env(MAILER_MAIL_SENDER)%'
            $mailerPassword: '%env(MAILER_PASSWORD)%'
            $mailerHost: '%env(MAILER_HOST)%'
            $mailerPort: '%env(MAILER_PORT)%'